
export const EDIT_OPERATOR_POPULATE="EDIT_OPERATOR_POPULATE";
export const READ_OPERATOR_SUCCESS ="READ_OPERATOR_SUCCESS";

export const CREATE_OPERATOR="CREATE_OPERATOR";
export const READ_OPERATOR="READ_OPERATOR";
export const UPDATE_OPERATOR="UPDATE_OPERATOR";
export const SIGNUP_OPERATOR="SIGNUP_OPERATOR";