export const CREATE_PCONTROL="CREATE_PCONTROL";
export const READ_PCONTROL="READ_PCONTROL";
export const UPDATE_PCONTROL="UPDATE_PCONTROL";

export const EDIT_PCONTROL_POPULATE="EDIT_PCONTROL_POPULATE";
export const READ_PCONTROL_SUCCESS ="READ_PCONTROL_SUCCESS";