export const CREATE_PRODUCT="CREATE_PRODUCT";
export const READ_PRODUCT="READ_PRODUCT";
export const UPDATE_PRODUCT="UPDATE_PRODUCT";

export const EDIT_PRODUCT_POPULATE="EDIT_PRODUCT_POPULATE";
export const READ_PRODUCT_SUCCESS ="READ_PRODUCT_SUCCESS";