export const CREATE_SALES="CREATE_SALES";
export const READ_SALES="READ_SALES";
export const UPDATE_SALES="UPDATE_SALES";

export const EDIT_SALES_POPULATE="EDIT_SALES_POPULATE";
export const UPDATE_SALES_LIST ="UPDATE_SALES_LIST";
export const READ_SALES_SUCCESS="READ_SALES_SUCCESS";